version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    reviewers:
      - xeptore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - xeptore
